### PR TITLE
fix overlapping section and program header error

### LINKED ISSUE #302: ELF loader crashes on `arm-linux-gnueabi-gcc` binary (`Found section header that overlaps with program header.`)
Take the following program (adapted from https://github.com/GaloisInc/macaw/issues/301#issuecomment-1183555233):

```c
// test.c
#include <stdint.h>

uint64_t x = 0;

int __attribute__((noinline)) test_strd() {
  x = 42;
  return x == 42;
}

int main() {
  test_strd();
  return 0;
}
```

And compile it with `arm-linux-gnueabi-gcc` like so:

```
$ arm-linux-gnueabi-gcc -nostartfiles -O2 -static test.c -o test.exe
```

And run it through this test harness:

<details>

```hs
-- Bug.hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ImplicitParams #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
module Main (main) where

import           Control.Lens ( (^.) )
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as BS8
import qualified Data.ElfEdit as Elf
import qualified Data.Foldable as F
import qualified Data.Map as Map
import           Data.Maybe ( mapMaybe )
import qualified Data.Parameterized.Classes as PC
import qualified Data.Parameterized.Nonce as PN
import           Data.Parameterized.Some ( Some(..) )
import           Data.Proxy ( Proxy(..) )

import qualified Language.ASL.Globals as ASL
import qualified Data.Macaw.Architecture.Info as MAI

import           Data.Macaw.AArch32.Symbolic ()
import qualified Data.Macaw.ARM as MA
import qualified Data.Macaw.ARM.ARMReg as MAR
import qualified Data.Macaw.Discovery as M
import qualified Data.Macaw.Symbolic as MS
import qualified Data.Macaw.Symbolic.Testing as MST
import qualified What4.Config as WC
import qualified What4.Expr as WE
import qualified What4.Expr.Builder as WEB
import qualified What4.Interface as WI
import qualified What4.ProblemFeatures as WPF
import qualified What4.Solver as WS

import qualified Lang.Crucible.Backend as CB
import qualified Lang.Crucible.Backend.Online as CBO
import qualified Lang.Crucible.Simulator as CS
import qualified Lang.Crucible.LLVM.MemModel as LLVM

main :: IO ()
main = do
  -- These are pass/fail in that the assertions in the "pass" set are true (and
  -- the solver returns Unsat), while the assertions in the "fail" set are false
  -- (and the solver returns Sat).
  let passRes = MST.SimulationResult MST.Unsat
  mkSymExTest passRes "test.exe"

hasTestPrefix :: Some (M.DiscoveryFunInfo arch) -> Maybe (BS8.ByteString, Some (M.DiscoveryFunInfo arch))
hasTestPrefix (Some dfi) = do
  bsname <- M.discoveredFunSymbol dfi
  if BS8.pack "test_" `BS8.isPrefixOf` bsname
    then return (bsname, Some dfi)
    else Nothing

mkSymExTest :: MST.SimulationResult -> FilePath -> IO ()
mkSymExTest expected exePath = do
  bytes <- BS.readFile exePath
  case Elf.decodeElfHeaderInfo bytes of
    Left (_, msg) -> fail ("Error parsing ELF header from file '" ++ show exePath ++ "': " ++ msg)
    Right (Elf.SomeElf ehi) -> do
      case Elf.headerClass (Elf.header ehi) of
        Elf.ELFCLASS32 ->
          symExTestSized expected ehi MA.arm_linux_info
        Elf.ELFCLASS64 -> fail "64 bit ARM is not supported"

symExTestSized :: MST.SimulationResult
               -> Elf.ElfHeaderInfo 32
               -> MAI.ArchitectureInfo MA.ARM
               -> IO ()
symExTestSized expected ehi archInfo = do
   (mem, discState) <- MST.runDiscovery ehi MST.toAddrSymMap archInfo
   let funInfos = Map.elems (discState ^. M.funInfo)
   let testEntryPoints = mapMaybe hasTestPrefix funInfos
   F.forM_ testEntryPoints $ \(name, Some dfi) -> do
     putStrLn ("Testing " ++ BS8.unpack name ++ " at " ++ show (M.discoveredFunAddr dfi))
     Some (gen :: PN.NonceGenerator IO t) <- PN.newIONonceGenerator
     sym <- WEB.newExprBuilder WEB.FloatRealRepr WE.EmptyExprBuilderState gen
     CBO.withYicesOnlineBackend sym CBO.NoUnsatFeatures WPF.noFeatures $ \bak -> do
       -- We are using the z3 backend to discharge proof obligations, so
       -- we need to add its options to the backend configuration
       let solver = WS.z3Adapter
       let backendConf = WI.getConfiguration sym
       WC.extendConfig (WS.solver_adapter_config_options solver) backendConf

       execFeatures <- MST.defaultExecFeatures (MST.SomeOnlineBackend bak)
       let Just archVals = MS.archVals (Proxy @MA.ARM) Nothing
       let extract = armResultExtractor archVals
       let ?memOpts = LLVM.defaultMemOptions
       simRes <- MST.simulateAndVerify solver WS.defaultLogData bak execFeatures archInfo archVals mem extract discState dfi
       if expected == simRes
         then putStrLn "Test passed"
         else fail $ "Expected " ++ show expected ++ ", but got " ++ show simRes

-- | ARM functions with a single scalar return value return it in %r0
--
-- Since all test functions must return a value to assert as true, this is
-- straightforward to extract
armResultExtractor :: ( CB.IsSymInterface sym
                      )
                   => MS.ArchVals MA.ARM
                   -> MST.ResultExtractor sym MA.ARM
armResultExtractor archVals = MST.ResultExtractor $ \regs _sp _mem k -> do
  let re = MS.lookupReg archVals regs (MAR.ARMGlobalBV (ASL.knownGlobalRef @"_R0"))
  k PC.knownRepr (CS.regValue re)
```
</details>

It will crash with the following error:

```
$ runghc-9.2 Bug.hs
Bug.hs: Found section header that overlaps with program header.
CallStack (from HasCallStack):
  error, called at src/Data/Macaw/Memory/ElfLoader.hs:1175:13 in macaw-base-0.3.15.6-inplace:Data.Macaw.Memory.ElfLoader
```

Curiously, the same error does _not_ occur if you instead compile this program with `musl-gcc`:

```
$ armv7m-linux-musleabi-gcc -nostartfiles -O2 -static test.c -o test.exe
$ runghc-9.2 Bug.hs
Testing test_strd at segment1+0x120
Test passed
```

### PR DESCRIPTION
**Pull request by danmatichuk**
This error is caused by a bug in the IntervalMap implementation prior to
0.6.2, which had inconsistent semantics for empty intervals
(see: https://github.com/bokesan/IntervalMap/issues/9)

fixes #302

### CODE REVIEW

File: macaw-aarch32/tests/arm/Makefile [hunk 1]
```diff
@@ -28,6 +28,10 @@ all: $(patsubst %.c,%-a32.exe,$(wildcard *.c)) $(patsubst %.c,%-t32.exe,$(wildca
 %-mixed.s: %-mixed.c
 	$(A32CC) -fno-stack-protector -S -c $< -o $@
 
+# doesn't work witn arm-none-eabi
```
Comment (RyanGlScott) [inline macaw-aarch32/tests/arm/Makefile:31]:
```suggestion
# doesn't work with arm-none-eabi
```

File: macaw-aarch32/tests/arm/Makefile [hunk 2]
```diff
@@ -28,6 +28,10 @@ all: $(patsubst %.c,%-a32.exe,$(wildcard *.c)) $(patsubst %.c,%-t32.exe,$(wildca
...
+test-empty-section.exe: test-empty-section.c
```
Comment (RyanGlScott) [inline macaw-aarch32/tests/arm/Makefile:32]: This `Makefile` says `test-empty-section.exe`, but the checked-in file is named `test-empty-section-a32.exe`. Which is it?

**Review by RyanGlScott — APPROVED** [review]
Thanks! I assume that this supersedes #317?

File: macaw-aarch32/tests/arm/Makefile (hunk 2 above)
Comment (danmatichuk) [reply macaw-aarch32/tests/arm/Makefile]: Good catch, it should have -a32 appended

File: macaw-aarch32/tests/arm/test-empty-section.c [hunk 3]
```diff
@@ -0,0 +1,14 @@
+// test.c
```
Comment (kquick) [inline macaw-aarch32/tests/arm/test-empty-section.c:1]: Can we add a reference to #302 here in this file so that someone browsing this code can get more details on the expected effects of building this test?

**Comment by RyanGlScott** [comment]
This is relevant to work I'm doing now in Macaw, so I'm going to take charge of landing this. (@danmatichuk, please let me know if there are still outstanding changes to be made here.)
