### PR TITLE
{aarch32,x86}-symbolic: A bit more work on exceptions

### LINKED ISSUE #369: aarch32-symbolic: Export `AArch32Exception`
... so that it can be caught by API users.

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #369.

### CODE REVIEW

File: x86_symbolic/src/Data/Macaw/X86/Crucible.hs [hunk 1]
```diff
@@ -131,14 +132,32 @@ withConcreteCountAndDir state val_size wrapped_count _wrapped_dir func =
...
+  show = show . pretty
 
 instance Exception MissingSemantics
 
+instance Pretty MissingSemantics where
+  pretty =
+    \case
+      MissingPrimFnSemantics fn ->
+        pretty "Symbolic execution semantics for x86 primitive function are not implemented yet:"
+          <+> I.runIdentity (MC.ppArchFn (I.Identity . liftAtomIn (pretty . regType)) fn)
```
Comment (langston-barrett) [inline x86_symbolic/src/Data/Macaw/X86/Crucible.hs:150]: This line is mostly copy-pasted from various spots, not sure it's correct but it does typecheck :shrug:

**Review by RyanGlScott — APPROVED** [review]
