### PR TITLE
Fix tail call classification

### LINKED ISSUE #285: `macaw-aarch32` classifies `b` instruction as jump rather than tail call
Given this program:

```c
#include <stdio.h>

void main() {
  printf("%d\n", 42);
}
```

If you compile it like so:

```
$ armv7m-linux-musleabi-gcc -O2 -nostartfiles -no-pie test.c -o test.exe
```

You'll end up with the following assembly:

```
$ armv7m-linux-musleabi-objdump -d test.exe

test.exe:     file format elf32-littlearm


Disassembly of section .plt:

00010198 <.plt>:
   10198:       e52de004        push    {lr}            ; (str lr, [sp, #-4]!)
   1019c:       e59fe004        ldr     lr, [pc, #4]    ; 101a8 <.plt+0x10>
   101a0:       e08fe00e        add     lr, pc, lr
   101a4:       e5bef008        ldr     pc, [lr, #8]!
   101a8:       00010e58        .word   0x00010e58

000101ac <printf@plt>:
   101ac:       e28fc600        add     ip, pc, #0, 12
   101b0:       e28cca10        add     ip, ip, #16, 20 ; 0x10000
   101b4:       e5bcfe58        ldr     pc, [ip, #3672]!        ; 0xe58

Disassembly of section .text:

000101b8 <main>:
   101b8:       e59f0008        ldr     r0, [pc, #8]    ; 101c8 <main+0x10>
   101bc:       e3a0102a        mov     r1, #42 ; 0x2a
   101c0:       e08f0000        add     r0, pc, r0
   101c4:       eafffff8        b       101ac <printf@plt>
   101c8:       00000004        .word   0x00000004
```

Notice that `main` tail-calls to `printf@plt` using a `b` instruction. When `macaw-aarch32` runs code discovery on this program, however, it classifies this as a jump rather than a tail call. Here is a test harness to demonstrate this happening:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ImplicitParams #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
module Main (main) where

import qualified Data.ByteString as BS
import qualified Data.ElfEdit as Elf
import           Data.Parameterized.Some ( Some(..) )
import qualified Prettyprinter as PP

import           Data.Macaw.AArch32.Symbolic ()
import qualified Data.Macaw.ARM as MA
import qualified Data.Macaw.Symbolic.Testing as MST

main :: IO ()
main = mkTest "test.exe"

mkTest :: FilePath -> IO ()
mkTest exePath = do
  bytes <- BS.readFile exePath
  case Elf.decodeElfHeaderInfo bytes of
    Left (_, msg) -> fail ("Error parsing ELF header from file '" ++ show exePath ++ "': " ++ msg)
    Right (Elf.SomeElf ehi) -> do
      case Elf.headerClass (Elf.header ehi) of
        Elf.ELFCLASS32 -> do
          (_mem, funInfos) <- MST.runDiscovery ehi MST.toAddrSymMap MA.arm_linux_info
          print $ PP.vcat $ map (\(Some x) -> PP.pretty x) funInfos
        Elf.ELFCLASS64 -> fail "64 bit ARM is not supported"
```
<details>

```
$ runghc-9.0.2 Main.hs
function main @ 0x101b8
0x101ac:
  ;  _R13 = stack_frame + 0
  ;  __PendingInterrupt = __AssertionFailure
  ;  __PendingPhysicalSError = __AssertionFailure
  ;  __Sleeping = __AssertionFailure
  ;  __UndefinedBehavior = __AssertionFailure
  ;  __UnpredictableBehavior = __AssertionFailure
  ;  PSTATE_IT in (8 0 0)
  ;  PSTATE_T in (1 0 0)
  ;  PSTATE_nRW in (1 1 1)
  ;  _R1 in (32 42 42)
  # 0x101ac 0x101ac: ADR_A1(xxxxxxxx.xxxxxxxx.10001111.xxxx0010) Rd 12, cond 14, imm12 1536
  # 0x101ac: ADR_A1(xxxxxxxx.xxxxxxxx.10001111.xxxx0010) Rd 12, cond 14, imm12 1536
  # 0x101ac: {PSTATE_T => 0x0 :: [1]
             ;_PC => 0x101b0
             ;_R12 => 0x101b4 :: [32]
             ;__AssertionFailure => false
             ;__BranchTaken => false
             ;__UndefinedBehavior => false
             ;__UnpredictableBehavior => false
             ;() => ()_0}
  # 0x101b0 0x101b0: ADD_i_A1(xxxxxxxx.xxxxxxxx.1000xxxx.xxxx0010) Rd 12, Rn 12, S 0, cond 14, imm12 2576
  # 0x101b0: ADD_i_A1(xxxxxxxx.xxxxxxxx.1000xxxx.xxxx0010) Rd 12, Rn 12, S 0, cond 14, imm12 2576
  # 0x101b0: {PSTATE_T => 0x0 :: [1]
             ;_PC => 0x101b4
             ;_R12 => 0x201b4 :: [32]
             ;__AssertionFailure => false
             ;__BranchTaken => false
             ;__UndefinedBehavior => false
             ;__UnpredictableBehavior => false
             ;() => ()_0}
  # 0x101b4 0x101b4: LDR_i_A1_pre(xxxxxxxx.xxxxxxxx.x011xxxx.xxxx0101) P 1, Rn 12, Rt 15, U 1, W 1, cond 14, imm12 3672
  # 0x101b4: LDR_i_A1_pre(xxxxxxxx.xxxxxxxx.x011xxxx.xxxx0101) P 1, Rn 12, Rt 15, U 1, W 1, cond 14, imm12 3672
  r248 := read_mem (0x2100c :: [32]) (bvle4)
  r249 := (bv_and r248 (0x1 :: [32]))
  r250 := (trunc r249 1)
  r251 := (eq r250 (0x1 :: [1]))
  r252 := (mux r251 (0x1 :: [1]) (0x0 :: [1]))
  # 0x101b4: {PSTATE_T => r252
             ;_PC => r248
             ;_R12 => 0x2100c :: [32]
             ;__AssertionFailure => false
             ;__BranchTaken => true
             ;__UndefinedBehavior => false
             ;__UnpredictableBehavior => false
             ;() => ()_0}
  tail_call
    { PSTATE_IT = 0x0 :: [8]
    , PSTATE_T = r252
    , PSTATE_nRW = 0x1 :: [1]
    , _PC = r248
    , _R12 = 0x2100c :: [32]
    , __AssertionFailure = false
    , __BranchTaken = true
    , __PendingInterrupt = false
    , __PendingPhysicalSError = false
    , __Sleeping = false
    , __UndefinedBehavior = false
    , __UnpredictableBehavior = false
    }
0x101b8:
  ;  _R13 = stack_frame + 0
  # 0x101b8 0x101b8: LDR_l_A1(xxxxxxxx.xxxxxxxx.x0x11111.xxxx010x) P 1, Rt 0, U 1, W 0, cond 14, imm12 8
  # 0x101b8: LDR_l_A1(xxxxxxxx.xxxxxxxx.x0x11111.xxxx010x) P 1, Rt 0, U 1, W 0, cond 14, imm12 8
  r122 := read_mem (0x101c8 :: [32]) (bvle4)
  # 0x101b8: {PSTATE_T => 0x0 :: [1]
             ;_PC => 0x101bc
             ;_R0 => r122
             ;__AssertionFailure => false
             ;__BranchTaken => false
             ;__UndefinedBehavior => false
             ;__UnpredictableBehavior => false
             ;() => ()_0}
  # 0x101bc 0x101bc: MOV_i_A1(xxxxxxxx.xxxxxxxx.1010OOOO.xxxx0011) Rd 1, S 0, cond 14, imm12 42, QuasiMask0 QuasiMask"("4): 0
  # 0x101bc: MOV_i_A1(xxxxxxxx.xxxxxxxx.1010OOOO.xxxx0011) Rd 1, S 0, cond 14, imm12 42, QuasiMask0 QuasiMask"("4): 0
  # 0x101bc: {PSTATE_T => 0x0 :: [1]
             ;_PC => 0x101c0
             ;_R1 => 0x2a :: [32]
             ;__AssertionFailure => false
             ;__BranchTaken => false
             ;__UndefinedBehavior => false
             ;__UnpredictableBehavior => false
             ;() => ()_0}
  # 0x101c0 0x101c0: ADD_r_A1(xxx0xxxx.xxxxxxxx.1000xxxx.xxxx0000) Rd 0, Rm 0, Rn 15, S 0, cond 14, imm5 0, type1 0
  # 0x101c0: ADD_r_A1(xxx0xxxx.xxxxxxxx.1000xxxx.xxxx0000) Rd 0, Rm 0, Rn 15, S 0, cond 14, imm5 0, type1 0
  r166 := (uext r122 65)
  r167 := (bv_add r166 (0x101c8 :: [65]))
  r168 := (trunc r167 32)
  # 0x101c0: {PSTATE_T => 0x0 :: [1]
             ;_PC => 0x101c4
             ;_R0 => r168
             ;__AssertionFailure => false
             ;__BranchTaken => false
             ;__UndefinedBehavior => false
             ;__UnpredictableBehavior => false
             ;() => ()_0}
  # 0x101c4 0x101c4: B_A1(xxxxxxxx.xxxxxxxx.xxxxxxxx.xxxx1010) cond 14, imm24 16777208
  # 0x101c4: B_A1(xxxxxxxx.xxxxxxxx.xxxxxxxx.xxxx1010) cond 14, imm24 16777208
  # 0x101c4: {_PC => 0x101ac
             ;__AssertionFailure => false
             ;__BranchTaken => true
             ;__UndefinedBehavior => false
             ;__UnpredictableBehavior => false}
  jump 0x101ac
    { PSTATE_IT = 0x0 :: [8]
    , PSTATE_T = 0x0 :: [1]
    , PSTATE_nRW = 0x1 :: [1]
    , _PC = 0x101ac
    , _R0 = r168
    , _R1 = 0x2a :: [32]
    , __AssertionFailure = false
    , __BranchTaken = true
    , __PendingInterrupt = false
    , __PendingPhysicalSError = false
    , __Sleeping = false
    , __UndefinedBehavior = false
    , __UnpredictableBehavior = false
    }
```
</details>

Notice the `jump 0x101ac` bit. While classifying it as a jump is not technically wrong, failing to classify it as a tail call means that it does not participate in `LookupFunctionHandle`, which makes it difficult to perform an action when invoking `printf@plt`.

### PR DESCRIPTION
**Pull request by travitch**
The tail call classifier came after the jump classifier, which was a problem
because it is less strict than the tail call classifier, meaning it would always
fire.  This commit moves direct jump to be the last classifier applied, giving
the others a chance.

Includes a test case in the ARM backend.

Fixes #285

### CODE REVIEW

**Review by RyanGlScott — APPROVED** [review]

File: symbolic/src/Data/Macaw/Symbolic/Testing.hs [hunk 1]
```diff
@@ -437,11 +432,56 @@ data ResultExtractor sym arch where
...
+  :: CFH.FnHandle args ret
+  -> CS.FnState p sym ext args ret
+  -> CS.FunctionBindings p sym ext
+  -> CS.FunctionBindings p sym ext
+addBinding hdl fstate (CS.FnBindings binds) =
+  CS.FnBindings (CFH.insertHandleMap hdl fstate binds)
+
 -- | The test harness does not currently support calling functions from test cases.
 --
 -- It could be modified to do so.
```
Comment (RyanGlScott) [inline symbolic/src/Data/Macaw/Symbolic/Testing.hs:457]: This comment is now out of date.

File: symbolic/src/Data/Macaw/Symbolic/Testing.hs [hunk 2]
```diff
@@ -437,11 +432,56 @@ data ResultExtractor sym arch where
...
+  :: (MM.MemWidth w)
+  => MM.Memory w
+  -> MM.MemWord w
+  -> Maybe (MM.MemSegmentOff w)
+resolveAbsoluteAddress mem addr =
+  listToMaybe [ segOff
+              | seg <- MM.memSegments mem
+              , let region = MM.segmentBase seg
+              , Just segOff <- return (MM.resolveRegionOff mem region addr)
+              ]
```
Comment (RyanGlScott) [inline symbolic/src/Data/Macaw/Symbolic/Testing.hs:445]: Note to self: if [`macaw-loader` is merged into `macaw`](https://github.com/GaloisInc/macaw/issues/283), we should consolidate this use of `resolveAbsoluteAddress` with the one currently defined in `macaw-loader`. (See GaloisInc/macaw-loader#11.)

File: base/src/Data/Macaw/Discovery.hs [hunk 3]
```diff
@@ -501,10 +501,10 @@ defaultClassifier = branchClassifier
                 <|> noreturnCallClassifier
                 <|> callClassifier
                 <|> returnClassifier
-                <|> directJumpClassifier
                 <|> jumpTableClassifier
                 <|> pltStubClassifier
                 <|> tailCallClassifier
+                <|> directJumpClassifier
```
Comment (RyanGlScott) [inline base/src/Data/Macaw/Discovery.hs:507]: If I understand correctly, this will currently yield some false positives when classifying tail calls. It would be worth leaving a comment explaining why this happens and to leave breadcrumbs in case we need to resolve this in the future.
